In [2]:
import numpy as np
import pandas as pd
from scipy.sparse.linalg import svds
from numpy.linalg import svd
import requests
import json

In [8]:
from model import RecSysOptions, RecSysMF

In [9]:
options = RecSysOptions()
options.core_directory

'/media/sf_shared_folder'

In [4]:
import os

In [5]:
os.path.dirname(os.path.dirname(os.path.abspath('__file__')))

'/media/sf_shared_folder'

In [17]:
weights = np.array([
    np.linspace(1, 3, 3),
    np.linspace(4, 6, 3),
    np.linspace(7, 9, 3),
]) / 10
weights

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [213]:
weights = np.array([
    np.linspace(1, 3, 3)
]) / 10
weights

array([[0.1, 0.2, 0.3]])

In [ ]:
# оценка * степень похожести = веса

In [41]:
marks = np.array([
    [3, 4, 5],
    [4, 4, 5],
    [5, 4, 5]
    ])
marks

array([[3, 4, 5],
       [4, 4, 5],
       [5, 4, 5]])

In [234]:
np.broadcast_arrays(weights, marks)[0]

(3, 3)

In [216]:
np.average(marks, axis=0, weights=weights.reshape(-1, 1))

TypeError: 1D weights expected when shapes of a and weights differ.

In [77]:
output = np.average(marks, axis=0, weights=weights)
output + np.std(marks[0])

array([5.31649658, 4.81649658, 5.81649658])

In [45]:
(0.1 * 3 + 0.4*4 + 0.7*5) / (0.1+0.4+0.7)

4.500000000000001

In [46]:
columns = [1, 4, 15]

In [82]:
df = pd.DataFrame(data=[output], columns=columns)
df

1    4    15
0  4.5  4.0  5.0

In [79]:
# max movie id
df.idxmax(axis=1).max()

15

In [92]:
output

array([4.5, 4. , 5. ])

In [131]:
marks

array([[3, 4, 5],
       [4, 4, 5],
       [5, 4, 5]])

In [201]:
# 0 = по y(по вертикали)
# 1 = по x(по горизонтали)
# матриця

# для множеств
maxar = np.argsort(-np.array(marks),axis=1)
maxar

array([[2, 1, 0],
       [2, 0, 1],
       [0, 2, 1]], dtype=int64)

In [209]:
arr = [1, 14, 5, 13]
arr.sort()
    arr[::-1][:2]

[14, 13]

In [211]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [240]:
marks

array([[3, 4, 5],
       [4, 4, 5],
       [5, 4, 5]])

In [239]:
np.argsort(-np.array(marks),axis=1)[:, :]

array([[2, 1, 0],
       [2, 0, 1],
       [0, 2, 1]], dtype=int64)

In [173]:
len(np.array(columns).shape)

1

In [259]:
np.argsort(-np.array(columns).reshape(1, -1), axis=1)[:, :2]

array([[2, 1]], dtype=int64)

In [68]:
from sklearn.metrics.pairwise import cosine_similarity

In [74]:
cosine_similarity(np.array([1, 2,3]).reshape(-1, 1).T, marks).T

array([[0.98270763],
       [0.95578964],
       [0.92113237]])

In [38]:
### predict ###

url = 'http://127.0.0.1:5000/api/predict'

params = {
    'movies_ratings': [['lord of the rings', 'Ed', 'Chorus'], [5, 4 , 3]],
    'M': 5
}

response = requests.post(url, json=params)
response, response.json()

(<Response [200]>,
 [['Clerks (1994)',
   'American Beauty (1999)',
   'Being John Malkovich (1999)',
   'Pulp Fiction (1994)',
   'Star Wars: Episode V - The Empire Strikes Back (1980)'],
  [5.0,
   4.803863162216332,
   4.52663433209319,
   4.495808054684974,
   4.468664148915199]])

In [39]:
### log ###

url = 'http://127.0.0.1:5000/api/log'

response = requests.get(url)
response, response.json()

(<Response [200]>,
 {'last 20 rows of logs': ['INFO::10-Mar-23 22:35:15::controller::predict::controller.py::64 result successfully predicted\n',
   'INFO::10-Mar-23 22:35:15::_internal::_log::_internal.py::224 127.0.0.1 - - [10/Mar/2023 22:35:15] "POST /api/predict HTTP/1.1" 200 -\n',
   'INFO::10-Mar-23 23:15:08::controller::predict::controller.py::22 reached /api/predict/ endpoint\n',
   'INFO::10-Mar-23 23:15:08::service::predict::service.py::33 Service predict method started\n',
   'INFO::10-Mar-23 23:15:08::model::predict::model.py::329 started predict method\n',
   'INFO::10-Mar-23 23:15:08::model::init_new_row::model.py::565 init_new_row method successfully executed\n',
   'INFO::10-Mar-23 23:15:08::model::normalize_row::model.py::176 started normalize_row method\n',
   'INFO::10-Mar-23 23:15:08::model::normalize_row::model.py::181 normalize_row method successfully executed\n',
   'INFO::10-Mar-23 23:15:08::model::predict::model.py::345 normalized_row row in predict method\n',


In [40]:
### info ###

url = 'http://127.0.0.1:5000/api/info'

response = requests.get(url)
response, response.json()

(<Response [200]>, {'message': 'Will be info'})

In [26]:
### reload ###

url = 'http://127.0.0.1:5000/api/reload'

response = requests.post(url)
response, response.json()

(<Response [200]>, {'Result': 'model successfully reloaded'})

In [25]:
### similar ###

url = 'http://127.0.0.1:5000/api/similar'

params = {
    'movie_name': 'Mad Max 2 (a.k.a. The Road Warrior)',
    'N': 3
}

response = requests.post(url, json=params)
response, response.json()

(<Response [200]>,
 [[3702, 2288, 2872],
  ['Mad Max (1979)', 'Thing, The (1982)', 'Excalibur (1981)']])

In [101]:
import fire

In [274]:
recsys.user_item_matrix

movie_id      1     2     3         4     5         6     7     8     9     \
user_id                                                                      
1         1.246121   0.0   0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   
2         0.000000   0.0   0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   
3         0.000000   0.0   0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   
4         0.000000   0.0   0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   
5         0.000000   0.0   0.0  0.000000   0.0 -1.001116   0.0   0.0   0.0   
...            ...   ...   ...       ...   ...       ...   ...   ...   ...   
6036      0.000000   0.0   0.0 -1.254827   0.0 -0.288773   0.0   0.0   0.0   
6037      0.000000   0.0   0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   
6038      0.000000   0.0   0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   
6039      0.000000   0.0   0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   
6040     -0.503352   0.0   0.0  0.000000   0.0  0.000000   0.0   0.0   0.0   

movie_id  10    ...  3943  3944  3945  3946  3947  3948  3949  3950  3951  \
user_id         ...                                                         
1          0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
2          0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
3          0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
4          0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
5          0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
...        ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
6036       0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
6037       0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
6038       0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
6039       0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
6040       0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

movie_id  3952  
user_id         
1          0.0  
2          0.0  
3          0.0  
4          0.0  
5          0.0  
...        ...  
6036       0.0  
6037       0.0  
6038       0.0  
6039       0.0  
6040       0.0  

[6040 rows x 3700 columns]

In [4]:
from settings import ROOT_DIR
ROOT_DIR

'C:\\Users\\Acer\\Machine Learning\\кусыны ьа натворил хуйни\\webapp'

In [4]:
from options import RecSysOptions

options = RecSysOptions()

options.core_directory

core_directory C:\Users\Acer\Machine Learning\кусыны ьа натворил хуйни
current C:\Users\Acer\Machine Learning\кусыны ьа натворил хуйни\model


'C:\\Users\\Acer\\Machine Learning\\кусыны ьа натворил хуйни'

In [1]:
# !pip install get-project-root

In [266]:
recsys.items_matrix[recsys.items_matrix['movie_id'] == 2858]

movie_id                   title        genres release_year
2789      2858  American Beauty (1999)  Comedy|Drama         1999

In [271]:
recsys.user_item_matrix.columns[3700]

IndexError: index 3700 is out of bounds for axis 0 with size 3700

In [33]:
!python ../model/model.py train --dataset='../data/train/ratings_train.dat'

trained


In [34]:
!python model.py evaluate --dataset='../data/test/ratings_test.dat'

trained
RMSE: 0.9474905338411924


In [35]:
%%time

!python model.py predict --dataset='../data/test/ratings_test.dat' --amount=6

trained
epoch 100
/media/sf_shared_folder/modelprediction_for_top_6_movies predicted
CPU times: user 1.19 s, sys: 151 ms, total: 1.34 s
Wall time: 1min 15s


In [36]:
!python model.py surprise_train --dataset='../data/train/ratings_train.dat'

trained


In [37]:
!python model.py surprise_evaluate --dataset='../data/test/ratings_test.dat'

trained
0.8580152386136243


In [1]:
import options

In [2]:
from options import RecSysOptions

In [331]:
movies = pd.read_csv( '/movies.dat', encoding='windows-1251',
                     names=['movie_id', 'title', 'genres'], sep='::', skiprows=0, engine='python')

# ratings_train = pd.read_csv( './../data/ratings_train.dat', names=['user_id', 'movie_id', 'rating', 'date'],
#                             sep='::', skiprows=0, engine='python')
# ratings_test = pd.read_csv( './../data/ratings_test.dat', names=['user_id', 'movie_id', 'rating', 'date'],
#                            sep='::', skiprows=0, engine='python')

In [3]:
from model import RecSysMF
from options import RecSysOptions

In [4]:
options = RecSysOptions()
recsys = RecSysMF(options)

In [5]:
recsys.train()

start train C:\Users\Acer\Machine Learning\кусыны ьа натворил хуйни\data/train/ratings_train.dat
start warmup C:\Users\Acer\Machine Learning\кусыны ьа натворил хуйни\model/store/model.csv
created  class
loaded model
load_Daat C:\Users\Acer\Machine Learning\кусыны ьа натворил хуйни\model/store/model.csv
fitted


In [6]:
recsys.evaluate()

start warmup C:\Users\Acer\Machine Learning\кусыны ьа натворил хуйни\model/store/model.csv
created  class
loaded model
load_Daat C:\Users\Acer\Machine Learning\кусыны ьа натворил хуйни\model/store/model.csv
          1         2         3         4         5         6         7     \
0     4.398970  4.176567  4.176818  4.159908  4.162921  4.160410  4.177996   
1     3.762805  3.664323  3.710087  3.735583  3.732440  3.682037  3.721840   
2     3.766429  3.863275  3.938165  3.918734  3.914483  3.920859  3.948941   
3     4.199042  4.121414  4.136080  4.121107  4.127962  4.107603  4.126419   
4     3.199656  3.080984  3.135731  3.126115  3.128298  3.084929  3.046404   
...        ...       ...       ...       ...       ...       ...       ...   
6035  4.022102  2.884253  3.443251  3.355444  3.391038  3.364954  3.220837   
6036  3.678527  3.615141  3.738418  3.689849  3.693157  3.595922  3.612162   
6037  3.903582  3.910329  3.886185  3.902854  3.901567  3.906855  3.909837   
6038  3.88281

0.9474905338411925

In [62]:
# test_df = recsys.load_ratings(recsys.options.test_data_path)
# test_df = recsys.create_user_item_rating_dataframe(recsys.users_matrix, recsys.items_matrix, recsys.ratings_test)

In [63]:
matrix_test = recsys.create_user_item_matrix(recsys.users_matrix, recsys.items_matrix, recsys.load_ratings(recsys.options.test_data_path))

3700

In [11]:
# movies_lack_in_test = set(train_columns) - set(test_columns)
# len(movies_lack_in_test)

603

In [12]:
# users_lack_in_test = set(train_index) - set(test_index)
# len(users_lack_in_test)

412

In [66]:
# new_movies_or_cols = np.append(test_columns, list(movies_lack_in_test))
# new_movies_or_cols

In [65]:
# new_users_or_rows = np.append(test_index, list(users_lack_in_test))
# new_users_or_rows

In [67]:
# print(matrix_test.shape)
#
# matrix_test

In [16]:
# new_users_data = np.empty((len(users_lack_in_test), matrix_test.shape[1]))
# new_users_data[:] = np.nan
# new_users_data.shape

(412, 3097)

In [17]:
# matrix_with_new_users = np.vstack([matrix_test.values, new_users_data])
# matrix_with_new_users.shape

(6040, 3097)

In [18]:
# new_users_data = np.empty((matrix_with_new_users.shape[0], len(movies_lack_in_test)))
# new_users_data[:] = np.nan
# new_users_data.T.shape

(603, 6040)

In [19]:
# new_data = np.hstack([matrix_with_new_users, new_users_data])
# new_data.shape

(6040, 3700)

In [68]:
# new_data

In [21]:
# new_df = pd.DataFrame(data=new_data, columns=new_movies_or_cols, index=new_users_or_rows)
# new_df = new_df.sort_index()
# new_df = new_df.reindex(sorted(new_df.columns), axis=1)

In [22]:
# from sklearn.metrics.pairwise import cosine_similarity

In [23]:
# normalized_new_df, mean_user_rating, std_user_rating = recsys.normalize_matrix(new_df)

In [24]:
# user_to_user_similarity = cosine_similarity(normalized_new_df.values, recsys.user_item_matrix).T

In [75]:
# user_to_user_similarity

In [41]:
# output = np.average(recsys.user_item_matrix, axis=0, weights=np.broadcast_arrays(user_to_user_similarity[0].reshape(-1, 1), recsys.user_item_matrix)[0])
# output

In [42]:
# output = output * std_user_rating[0] + mean_user_rating[0]

In [43]:
# best_movies_ids = np.argsort(-output.reshape(1, -1), axis=1)[:, :3]
# best_movies_ids

In [70]:
# best_movies_cols_ids = recsys.model.data.columns.values[best_movies_ids][0]
# best_movies_cols_ids

In [71]:
# films = recsys.find_items_by_ids(best_movies_cols_ids)
#
# # print('films', films)
#
# films.sort_values('movie_id', ascending=False)['title'].values.tolist()
#
# movies_names = recsys.sort_items_by_ids(films, best_movies_cols_ids)
# movies_names

In [74]:
# best_movies_marks = output[::-1][:3]
#
# # print('best_movies_marks', best_movies_marks)
# #
# # print('result', movies_names, best_movies_marks)
#
# best_movies_marks[best_movies_marks > 5] = 5
# best_movies_marks[best_movies_marks < 0] = 0
#
# best_movies_marks

In [73]:
# mv = [movies_names]*5
# bm = [best_movies_marks]*5

In [72]:
# mv

In [80]:
M = 7

In [85]:
%%time

matrix_test = recsys.create_user_item_matrix(recsys.users_matrix, recsys.items_matrix, recsys.load_ratings(recsys.options.test_data_path))

# movies
train_columns = recsys.model.data.columns.values
train_index = recsys.model.data.index.values

# users
test_columns = matrix_test.columns.values
test_index = matrix_test.index.values - 1

movies_lack_in_test = set(train_columns) - set(test_columns)
users_lack_in_test = set(train_index) - set(test_index)

new_movies_or_cols = np.append(test_columns, list(movies_lack_in_test))
new_users_or_rows = np.append(test_index, list(users_lack_in_test))

new_users_data = np.empty((len(users_lack_in_test), matrix_test.shape[1]))
new_users_data[:] = np.nan

matrix_with_new_users = np.vstack([matrix_test.values, new_users_data])

new_users_data = np.empty((matrix_with_new_users.shape[0], len(movies_lack_in_test)))
new_users_data[:] = np.nan

new_data = np.hstack([matrix_with_new_users, new_users_data])

new_df = pd.DataFrame(data=new_data, columns=new_movies_or_cols, index=new_users_or_rows)
new_df = new_df.sort_index()
new_df = new_df.reindex(sorted(new_df.columns), axis=1)

normalized_new_df, mean_user_rating, std_user_rating = recsys.normalize_matrix(new_df)

CPU times: total: 1.12 s
Wall time: 1.04 s


In [86]:
%%time

user_to_user_similarity = cosine_similarity(normalized_new_df.values, recsys.user_item_matrix).T

movies = np.chararray([])
mov_nam = []
markss = []

for (asd, user_data) in enumerate(zip(user_to_user_similarity, std_user_rating, mean_user_rating)):

    if asd % 50 == 0 and asd > 0:
        print(f'epoch {asd}')
        break
    output = np.average(recsys.user_item_matrix, axis=0, weights=np.broadcast_arrays(user_data[0].reshape(-1, 1), recsys.user_item_matrix)[0])
    output = output * user_data[1] + user_data[2]
    best_movies_ids = np.argsort(-output.reshape(1, -1), axis=1)[:, :M]

    best_movies_cols_ids = recsys.model.data.columns.values[best_movies_ids][0]

    films = recsys.find_items_by_ids(best_movies_cols_ids)

    films.sort_values('movie_id', ascending=False)['title'].values.tolist()

    movies_names = recsys.sort_items_by_ids(films, best_movies_cols_ids)

    best_movies_marks = output[::-1][:M]

    best_movies_marks[best_movies_marks > 5] = 5
    best_movies_marks[best_movies_marks < 0] = 0

    mov_nam.append(movies_names)
    markss.append(best_movies_marks)



epoch 50
CPU times: total: 12.4 s
Wall time: 5.56 s


In [83]:
%%time

cols = []
for i in range(1, M+1):
    cols.append(f'movie_name_{i}')
    cols.append(f'mark_{i}')

cols

CPU times: total: 0 ns
Wall time: 0 ns


['movie_name_1',
 'mark_1',
 'movie_name_2',
 'mark_2',
 'movie_name_3',
 'mark_3',
 'movie_name_4',
 'mark_4',
 'movie_name_5',
 'mark_5',
 'movie_name_6',
 'mark_6',
 'movie_name_7',
 'mark_7']

In [84]:
%%time

df = []

cols = []
for i in range(1, M+1):
    cols.append(f'movie_name_{i}')
    cols.append(f'mark_{i}')


for name, mark in zip(mov_nam, markss):
    row_data = []
    for i in range(M):
        row_data.append(name[i])
        row_data.append(mark[i])
    df.append(row_data)

res_df = pd.DataFrame(data=df, columns=cols)
res_df.index = res_df.index + 1
res_df

CPU times: total: 31.2 ms
Wall time: 54.8 ms


movie_name_1    mark_1  \
1                        Raiders of the Lost Ark (1981)  4.678648   
2             Star Wars: Episode IV - A New Hope (1977)  3.016259   
3                                      Toy Story (1995)  3.000000   
4                                      Toy Story (1995)  5.000000   
5                                          Fargo (1996)  3.608560   
...                                                 ...       ...   
6036          Star Wars: Episode IV - A New Hope (1977)  3.382858   
6037                              Godfather, The (1972)  3.800931   
6038                                   Toy Story (1995)  2.000000   
6039  Star Wars: Episode V - The Empire Strikes Back...  4.002503   
6040                              Godfather, The (1972)  3.336558   

                                           movie_name_2    mark_2  \
1                                   Forrest Gump (1994)  4.664082   
2                               Schindler's List (1993)  2.999122   
3                               Mole People, The (1956)  3.000000   
4                               Mole People, The (1956)  5.000000   
5                                American Beauty (1999)  3.592230   
...                                                 ...       ...   
6036                              Godfather, The (1972)  3.366507   
6037  Star Wars: Episode V - The Empire Strikes Back...  3.804631   
6038                            Mole People, The (1956)  2.000000   
6039                     Raiders of the Lost Ark (1981)  4.000449   
6040                             American Beauty (1999)  3.363494   

                                   movie_name_3    mark_3  \
1                         Godfather, The (1972)  4.663638   
2                    Saving Private Ryan (1998)  3.027143   
3                            Swamp Thing (1982)  3.000000   
4                            Swamp Thing (1982)  5.000000   
5                   Being John Malkovich (1999)  3.547457   
...                                         ...       ...   
6036                         Matrix, The (1999)  3.365915   
6037                    Schindler's List (1993)  3.806333   
6038                         Swamp Thing (1982)  2.000000   
6039  Star Wars: Episode IV - A New Hope (1977)  4.000273   
6040                               Fargo (1996)  3.358468   

                                           movie_name_4    mark_4  \
1                      Silence of the Lambs, The (1991)  4.704070   
2                        Raiders of the Lost Ark (1981)  3.040636   
3                                 Pork Chop Hill (1959)  3.000000   
4                                 Pork Chop Hill (1959)  5.000000   
5                            Usual Suspects, The (1995)  3.702938   
...                                                 ...       ...   
6036  Star Wars: Episode V - The Empire Strikes Back...  3.416069   
6037                     Raiders of the Lost Ark (1981)  3.833156   
6038                              Pork Chop Hill (1959)  2.000000   
6039                                  Casablanca (1942)  4.017165   
6040                     Raiders of the Lost Ark (1981)  3.433696   

                                           movie_name_5    mark_5  \
1                                    Toy Story 2 (1999)  4.691725   
2                      Shawshank Redemption, The (1994)  3.019613   
3                           Run Silent, Run Deep (1958)  3.000000   
4                           Run Silent, Run Deep (1958)  5.000000   
5                                   Pulp Fiction (1994)  3.533204   
...                                                 ...       ...   
6036                             American Beauty (1999)  3.366954   
6037                   Silence of the Lambs, The (1991)  3.751780   
6038                        Run Silent, Run Deep (1958)  2.000000   
6039                            Schindler's List (1993)  3.980662   
6040  Star Wars: Episode V - The Empire Strikes Back...  3.33436

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [221]:
pred = pd.DataFrame(data=np.array(mov), columns=['best movie'], index=new_df.index+1)

pred.to_csv('predictions')

In [159]:
user_to_user_similarity

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.02693332,  0.        ],
       [ 0.02338398,  0.00088339,  0.00092843, ...,  0.00093225,
         0.00087757, -0.00656907],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
        -0.02036266,  0.00121229],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.00309368,  0.00246209,  0.        , ...,  0.        ,
         0.        ,  0.02482085],
       [ 0.01227757,  0.00309147,  0.00890098, ...,  0.00893757,
         0.01436533,  0.00768029]])

In [254]:
recsys.items_matrix[5: 12].sort_values('movie_id', ascending=False)['title'].values.tolist()

['Dracula: Dead and Loving It (1995)',
 'American President, The (1995)',
 'GoldenEye (1995)',
 'Sudden Death (1995)',
 'Tom and Huck (1995)',
 'Sabrina (1995)',
 'Heat (1995)']

In [6]:
import os

# get current directory
path = os.getcwd()
print("Current Directory", path)

# prints parent directory
print(os.path.abspath(os.path.join(os.getcwd(), os.pardir)) + '/data')

Current Directory C:\Users\Acer\Machine Learning\кусыны ьа натворил хуйни\webapp
C:\Users\Acer\Machine Learning\кусыны ьа натворил хуйни/data


In [8]:
%%time

recsys.train()

start train
None
start warmup
created model
fitted
CPU times: total: 53.5 s
Wall time: 47.2 s


In [5]:
%%time

user_id = 50
data = [['Toy Story', 'Lord of the rings', 'Terminator', 'Ed'], [5, 5, 4, 5]]
output, prob_values = recsys.predict(data)

movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
0          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   

movie_id  3943  3944  3945  3946  3947  3948  3949  3950  3951  3952  
0          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[1 rows x 3700 columns]
movie_id  1     2     3     4     5     6     7     8     9     10    ...  \
0            5   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   

movie_id  3943  3944  3945  3946  3947  3948  3949  3950  3951  3952  
0          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[1 rows x 3700 columns]
[[ 0.05087267]
 [ 0.        ]
 [ 0.        ]
 ...
 [ 0.        ]
 [ 0.        ]
 [-0.00807251]]
CPU times: total: 1.23 s
Wall time: 492 ms


In [7]:
options.model_data_path

'C:\\Users\\Acer\\Machine Learning\\кусыны ьа натворил хуйни\\model/store/model.csv'

In [7]:
'2116' in recsys.model.data.columns

False

In [5]:
recsys.items_matrix

movie_id                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878      3948             Meet the Parents (2000)   
3879      3949          Requiem for a Dream (2000)   
3880      3950                    Tigerland (2000)   
3881      3951             Two Family House (2000)   
3882      3952               Contender, The (2000)   

                            genres release_year  
0      Animation|Children's|Comedy         1995  
1     Adventure|Children's|Fantasy         1995  
2                   Comedy|Romance         1995  
3                     Comedy|Drama         1995  
4                           Comedy         1995  
...                            ...          ...  
3878                        Comedy         2000  
3879                         Drama         2000  
3880                         Drama         2000  
3881                         Drama         2000  
3882                Drama|Thriller         2000  

[3883 rows x 4 columns]

In [4]:
recsys.evaluate()

0.9474905338411924

In [7]:
model.calculate_rmse()

movie_id      1         2         3         4         5         6     \
user_id                                                                
1         4.313329  3.565448  3.387143  3.219692  3.424951  4.065617   
2         3.263242  3.804786  3.666072  3.338980  3.049609  3.439470   
3         4.094688  3.750604  3.230408  3.277175  3.618950  3.135103   
4         3.454915  3.454915  3.454915  3.454915  3.454915  3.454915   
5         3.890321  2.733405  2.644051  3.214182  3.788217  4.114239   
...            ...       ...       ...       ...       ...       ...   
6036      3.651390  3.651390  3.651390  3.651390  3.651390  3.651390   
6037      3.243414  3.008875  3.365973  2.649871  2.587904  2.886564   
6038      3.415863  3.844136  3.778038  3.133114  3.999066  3.744656   
6039      3.778038  3.778038  3.778038  3.778038  3.778038  3.778038   
6040      3.821310  4.179958  3.560638  3.859176  3.828034  3.657254   

movie_id      7         8         9         10    ...      3943      3944  \
user_id                                           ...                       
1         3.858191  3.309063  3.002969  3.669563  ...  2.891565  2.553389   
2         3.174432  3.516995  2.696286  2.643805  ...  3.276381  2.881918   
3         3.325029  3.454915  3.520034  3.620789  ...  3.454915  3.454915   
4         3.454915  3.454915  3.454915  3.454915  ...  3.572722  2.770162   
5         3.856012  3.953367  4.008304  3.275975  ...  3.311281  3.459240   
...            ...       ...       ...       ...  ...       ...       ...   
6036      3.651390  3.651390  3.651390  3.651390  ...  3.590743  3.191500   
6037      3.328627  3.280877  3.615346  3.440053  ...  4.147482  3.545762   
6038      3.219211  3.780847  3.778038  2.996352  ...  3.778038  3.778038   
6039      3.778038  3.778038  3.778038  3.778038  ...  3.575815  3.797664   
6040      4.129900  3.905848  4.024515  3.431420  ...  3.861011  3.861011   

movie_id      3945      3946      3947      3948      3949      3950  \
user_id                                                                
1         2.731832  2.133306  2.152441  2.900120  3.195157  3.340525   
2         3.320708  3.171654  3.032676  3.408148  3.784753  4.195297   
3         3.454915  3.454915  3.454915  3.454915  3.454915  3.454915   
4         2.745071  3.311142  2.795781  3.950569  3.271300  3.229498   
5         4.046415  2.319926  3.466577  3.410976  3.620704  2.942035   
...            ...       ...       ...       ...       ...       ...   
6036      2.355012  3.369217  3.080346  2.999354  3.530547  3.382624   
6037      4.171388  4.068540  3.405964  3.728195  3.551051  3.991591   
6038      3.778038  3.778038  3.778038  3.778038  3.778038  3.778038   
6039      4.106829  3.496713  3.148984  4.304795  3.707990  2.682514   
6040      3.861011  3.861011  3.861011  3.861011  3.861011  3.861011   

movie_id      3951      3952  
user_id                       
1         3.608748  3.613493  
2         2.389130  3.334123  
3         3.454915  3.454915  
4         2.775991  2.646518  
5         2.965108  3.637991  
...            ...       ...  
6036      3.034001  3.176289  
6037      3.778038  3.674340  
6038      3.778038  3.778038  
6039      3.367161  3.451437  
6040      3.861011  3.861011  

[6040 rows x 3700 columns]

In [7]:
import numpy as np

In [11]:
user_similaity = np.zeros((1, 6040))

In [13]:
user_similaity.T

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [332]:
ratings_test

user_id  movie_id  rating       date
0         3842      1645       2  976513704
1         2928       246       4  971556036
2         5718        25       3  958588034
3           53      1177       5  977986413
4          134         6       2  978038386
...        ...       ...     ...        ...
50000     1389      2987       4  974769357
50001     2012      3712       3  974680318
50002     1679      3219       3  974709659
50003     1890       800       5  974694814
50004      499      2243       3  976212980

[50005 rows x 4 columns]

In [329]:
train_set, test_set = import_data()

In [313]:
matrix_demeaned.shape

(5628, 3097)

In [299]:
n_users = train_set['user_id'].nunique()
n_movies = train_set['movie_id'].nunique()

print('Number of users:', n_users)
print('Number of movies:', n_movies)

Number of users: 6040
Number of movies: 3700


In [344]:
matrix = create_movie_user_rating_matrix(train_set)

In [345]:
matrix_demeaned, mean_user_rating = normalize_matrix(matrix)

In [346]:
sparsity = round(1.0 - matrix.shape[0] / float(n_users * n_movies), 5)
print('The sparsity level of MovieLens1M dataset is ' +  str(sparsity * 100) + '%')

The sparsity level of MovieLens1M dataset is 99.973%


In [469]:
%%time

# train

u, sigma, vt = svds(matrix_demeaned, k=1500)  # Number of singular values and vectors to compute

Wall time: 1min 23s


In [470]:
sigma_diag_matrix = np.diag(sigma)

In [471]:
sigma_diag_matrix.shape

(1500, 1500)

In [472]:
all_user_predicted_ratings = np.dot(np.dot(u, sigma_diag_matrix), vt) + mean_user_rating

preds = pd.DataFrame(abs(all_user_predicted_ratings), columns = matrix.columns)

preds

movie_id      1         2         3         4         5         6     \
0         4.985579  0.059449  0.071026  0.213995  0.034762  0.017546   
1         0.050225  0.158209  0.128727  0.035028  0.046431  0.051035   
2         0.000599  0.166642  0.043806  0.141172  0.057862  0.065778   
3         0.003157  0.017706  0.022104  0.036406  0.000870  0.010761   
4         0.000322  0.157598  0.166119  0.134881  0.105086  2.069467   
...            ...       ...       ...       ...       ...       ...   
6035      0.031398  0.027929  0.080378  1.796561  0.082473  3.065420   
6036      0.040195  0.054268  0.070126  0.103058  0.073634  0.049750   
6037      0.022556  0.143824  0.053868  0.030585  0.133838  0.033356   
6038      0.010954  0.017445  0.141095  0.191303  0.043225  0.104167   
6039      3.040022  0.024444  0.143046  0.245750  0.002753  0.005158   

movie_id      7         8         9         10    ...      3943      3944  \
0         0.104463  0.114465  0.166680  0.004528  ...  0.018611  0.051363   
1         0.219368  0.044569  0.204314  0.015918  ...  0.066078  0.038532   
2         0.078996  0.109665  0.148491  0.048181  ...  0.106708  0.008081   
3         0.095679  0.029886  0.066654  0.036498  ...  0.121229  0.033286   
4         0.021200  0.150827  0.073457  0.046669  ...  0.045348  0.090912   
...            ...       ...       ...       ...  ...       ...       ...   
6035      0.078918  0.213783  0.025649  0.008092  ...  0.021434  0.043988   
6036      0.114558  0.172374  0.078522  0.135230  ...  0.257354  0.014630   
6037      0.013478  0.086750  0.004329  0.035888  ...  0.045188  0.018979   
6038      0.017120  0.204919  0.123681  0.025588  ...  0.093557  0.068047   
6039      0.092740  0.002983  0.222069  0.065051  ...  0.158573  0.039143   

movie_id      3945      3946      3947      3948      3949      3950  \
0         0.015641  0.029646  0.093843  0.019544  0.050339  0.141392   
1         0.060089  0.026659  0.184084  0.012921  0.170177  0.027419   
2         0.097837  0.129108  0.166187  0.006777  0.099810  0.100117   
3         0.017839  0.011614  0.013813  0.001213  0.010804  0.022704   
4         0.038524  0.024030  0.084158  0.115942  0.085640  0.284243   
...            ...       ...       ...       ...       ...       ...   
6035      0.056971  0.058520  0.151509  0.028739  0.074954  0.155875   
6036      0.019518  0.029364  0.277982  0.037605  0.107778  0.065530   
6037      0.031210  0.005795  0.048034  0.016737  0.081308  0.137197   
6038      0.149185  0.021599  0.166670  0.061880  0.064763  0.096415   
6039      0.000243  0.135921  0.168836  0.025111  0.072122  0.068407   

movie_id      3951      3952  
0         0.007380  0.027534  
1         0.108000  0.087112  
2         0.012887  0.033637  
3         0.003082  0.048077  
4         0.256928  0.004439  
...            ...       ...  
6035      0.109872  0.022130  
6036      0.172007  0.157559  
6037      0.078399  0.023241  
6038      0.185600  0.038211  
6039      0.035043  0.090441  

[6040 rows x 3700 columns]

In [473]:
preds.T[3041][1644]

0.07467419390599193

In [474]:
movie_ids = preds.columns.values

In [475]:
movie_ids

array([   1,    2,    3, ..., 3950, 3951, 3952], dtype=int64)

In [476]:
real_marks = []
predictions = []
for index, row in test_set.iterrows():
    user_id = row['user_id'] - 1
    movie_id = row['movie_id'] - 1
    rating = row['rating']
    if movie_id in movie_ids:
        real_marks.append(rating)
        predictions.append(preds.T[user_id][movie_id])
  mean_squared_error(real_marks, predictions, squared=False)      
        
        
#         print(user_id, movie_id, rating)
#         print(preds.T[user_id][movie_id])

In [477]:
mean_squared_error(real_marks, predictions, squared=False)

3.361151550701443

In [307]:
from sklearn.metrics import mean_squared_error
from math import sqrt

def rmse(prediction, ground_truth):
    prediction = prediction[ground_truth.nonzero()].flatten()
    
    ground_truth = ground_truth[ground_truth.nonzero()].flatten()
    
    return sqrt(mean_squared_error(prediction, ground_truth))

In [308]:
matrix.shape

(5628, 3097)

In [320]:
preds.shape

(5628, 3097)

In [351]:
# выводим метрику
print('User-based CF MSE: ' + str(rmse(preds.values, matrix.values)))

User-based CF MSE: 2.282514161601292


In [339]:
preds

movie_id      1         2         3         4         5         6     \
0        -0.000660 -0.016424  0.027023 -0.015484  0.041822  0.003945   
1        -0.003082 -0.001373 -0.018678 -0.016947  0.073440  0.016424   
2        -0.000430  0.004153  0.000359 -0.001032 -0.008754  0.002946   
3        -0.002326  0.030807  0.001950 -0.038053  0.017005 -0.004548   
4         0.002837  0.017596  0.035146  0.024914  0.045143 -0.026363   
...            ...       ...       ...       ...       ...       ...   
5623      0.009418  0.010052  0.015213  0.000504  0.070826 -0.011582   
5624     -0.012215  0.005987 -0.014744 -0.021743  0.001908  0.001702   
5625      0.000118 -0.000250  0.001074  0.003903  0.003965 -0.001600   
5626      0.003518 -0.001757 -0.008249  0.013243 -0.024033 -0.002121   
5627      0.000485  0.024048  0.013399 -0.002279  0.020317 -0.005645   

movie_id      7         8         9         10    ...      3943      3944  \
0        -0.002268 -0.029260 -0.014424  0.008088  ... -0.000497  0.001212   
1         0.022730  0.006129  0.015747 -0.001800  ... -0.023446 -0.004787   
2         0.002526 -0.011375 -0.006920 -0.000614  ...  0.010325 -0.000441   
3        -0.036594  0.005584  0.013453 -0.000729  ... -0.018111 -0.002165   
4        -0.018681  0.012608  0.039458  0.003640  ... -0.045541 -0.002169   
...            ...       ...       ...       ...  ...       ...       ...   
5623      0.028480 -0.002541  0.019103  0.028484  ...  0.002523 -0.004352   
5624      0.042025  0.023128 -0.036530  0.006183  ...  0.069716  0.011698   
5625      0.000547 -0.005015  0.002304 -0.001449  ... -0.005943  0.000687   
5626      0.067111 -0.039889 -0.008747  0.006352  ... -0.008586  0.001464   
5627     -0.057213 -0.146342 -0.010388 -0.016723  ...  0.021135  0.000838   

movie_id      3945      3946      3947      3948      3949      3950  \
0         0.001282 -0.001312 -0.042283  0.002514 -0.006752  0.005232   
1        -0.015304 -0.041604  0.003106  0.000725 -0.004439  0.013094   
2        -0.002193 -0.003243 -0.000748  0.003095 -0.001640  0.007207   
3         0.004753 -0.022980 -0.034919 -0.005951 -0.004146  0.011381   
4        -0.006172  0.003497  0.004483 -0.001384 -0.042544  0.014004   
...            ...       ...       ...       ...       ...       ...   
5623     -0.024686  0.028940 -0.020476 -0.010257 -0.019584  0.016213   
5624     -0.011595  0.003807  0.303038  0.003680  0.002179  0.003197   
5625      0.000398  0.002561  0.004706  0.001447 -0.001308 -0.000059   
5626     -0.006993 -0.008339  0.057332  0.010163 -0.003058 -0.035871   
5627     -0.003139 -0.037708 -0.018734 -0.012047 -0.000894 -0.042934   

movie_id      3951      3952  
0        -0.011195  0.001936  
1         0.000836  0.020175  
2        -0.001962 -0.000210  
3        -0.013752  0.014176  
4        -0.013222  0.000296  
...            ...       ...  
5623      0.002926 -0.011897  
5624     -0.006172  0.031532  
5625     -0.000420 -0.001140  
5626      0.010307 -0.023477  
5627      0.002611 -0.012833  

[5628 rows x 3097 columns]

In [454]:
mean_squared_error(preds.values, matrix.values, squared=False)

0.12389799141359445

In [ ]:
def train()

In [234]:
from surprise import Reader, Dataset, SVD, SVDpp
from surprise import accuracy

In [237]:
matrix_demeaned

movie_id      1         2         3         4         5         6     \
user_id                                                                
1        -0.004521 -0.004521 -0.004521 -0.004521 -0.004521 -0.004521   
2        -0.006781 -0.006781 -0.006781 -0.006781 -0.006781 -0.006781   
3        -0.000969 -0.000969 -0.000969 -0.000969 -0.000969 -0.000969   
4        -0.003229 -0.003229 -0.003229 -0.003229 -0.003229 -0.003229   
5        -0.008072 -0.008072 -0.008072 -0.008072 -0.008072 -0.008072   
...            ...       ...       ...       ...       ...       ...   
6036     -0.059735 -0.059735 -0.059735 -0.059735 -0.059735 -0.059735   
6037     -0.012270 -0.012270 -0.012270 -0.012270 -0.012270 -0.012270   
6038     -0.000646 -0.000646 -0.000646 -0.000646 -0.000646 -0.000646   
6039     -0.006458 -0.006458 -0.006458 -0.006458 -0.006458 -0.006458   
6040     -0.018405 -0.018405 -0.018405 -0.018405 -0.018405 -0.018405   

movie_id      7         8         9         10    ...      3943      3944  \
user_id                                           ...                       
1        -0.004521 -0.004521 -0.004521 -0.004521  ... -0.004521 -0.004521   
2        -0.006781 -0.006781 -0.006781 -0.006781  ... -0.006781 -0.006781   
3        -0.000969 -0.000969 -0.000969 -0.000969  ... -0.000969 -0.000969   
4        -0.003229 -0.003229 -0.003229 -0.003229  ... -0.003229 -0.003229   
5        -0.008072 -0.008072 -0.008072 -0.008072  ... -0.008072 -0.008072   
...            ...       ...       ...       ...  ...       ...       ...   
6036     -0.059735 -0.059735 -0.059735 -0.059735  ... -0.059735 -0.059735   
6037     -0.012270 -0.012270 -0.012270 -0.012270  ... -0.012270 -0.012270   
6038     -0.000646 -0.000646 -0.000646 -0.000646  ... -0.000646 -0.000646   
6039     -0.006458 -0.006458 -0.006458 -0.006458  ... -0.006458 -0.006458   
6040     -0.018405 -0.018405 -0.018405 -0.018405  ... -0.018405 -0.018405   

movie_id      3945      3946      3947      3948      3949      3950  \
user_id                                                                
1        -0.004521 -0.004521 -0.004521 -0.004521 -0.004521 -0.004521   
2        -0.006781 -0.006781 -0.006781 -0.006781 -0.006781 -0.006781   
3        -0.000969 -0.000969 -0.000969 -0.000969 -0.000969 -0.000969   
4        -0.003229 -0.003229 -0.003229 -0.003229 -0.003229 -0.003229   
5        -0.008072 -0.008072 -0.008072 -0.008072 -0.008072 -0.008072   
...            ...       ...       ...       ...       ...       ...   
6036     -0.059735 -0.059735 -0.059735 -0.059735 -0.059735 -0.059735   
6037     -0.012270 -0.012270 -0.012270 -0.012270 -0.012270 -0.012270   
6038     -0.000646 -0.000646 -0.000646 -0.000646 -0.000646 -0.000646   
6039     -0.006458 -0.006458 -0.006458 -0.006458 -0.006458 -0.006458   
6040     -0.018405 -0.018405 -0.018405 -0.018405 -0.018405 -0.018405   

movie_id      3951      3952  
user_id                       
1        -0.004521 -0.004521  
2        -0.006781 -0.006781  
3        -0.000969 -0.000969  
4        -0.003229 -0.003229  
5        -0.008072 -0.008072  
...            ...       ...  
6036     -0.059735 -0.059735  
6037     -0.012270 -0.012270  
6038     -0.000646 -0.000646  
6039     -0.006458 -0.006458  
6040     -0.018405 -0.018405  

[5628 rows x 3097 columns]

In [430]:
ratings_train

user_id  movie_id  rating       date
0          3539      2478       5  966882141
1          5795       377       2  958143844
2          3513      3526       4  966974170
3          4176       924       5  965330955
4          4657      1960       4  975803771
...         ...       ...     ...        ...
950193     4148       969       5  965343002
950194     4115      2393       5  965363379
950195     3721      1061       4  966225726
950196     4946      1172       4  962641424
950197      505       541       5  976209793

[950198 rows x 4 columns]

In [29]:
ratings_test = pd.read_csv( './../data/ratings_test.dat', names=['user_id', 'movie_id', 'rating', 'date'],
                               sep='::', skiprows=0, engine='python')

FileNotFoundError: [Errno 2] No such file or directory: './../data/ratings_test.dat'

In [432]:
ratings_test = pd.read_csv( './../data/ratings_test.dat', names=['user_id', 'movie_id', 'rating', 'date'],
                               sep='::', skiprows=0, engine='python')

user_id  movie_id  rating       date
0         3842      1645       2  976513704
1         2928       246       4  971556036
2         5718        25       3  958588034
3           53      1177       5  977986413
4          134         6       2  978038386
...        ...       ...     ...        ...
50000     1389      2987       4  974769357
50001     2012      3712       3  974680318
50002     1679      3219       3  974709659
50003     1890       800       5  974694814
50004      499      2243       3  976212980

[50005 rows x 4 columns]

In [38]:
recsys.ratings_train

NameError: name 'recsys' is not defined

In [28]:
reader = Reader(rating_scale=(1, 5))

dataset_train = Dataset.load_from_df(ratings_train[['user_id', 'movie_id', 'rating']], reader=reader)

svd = SVD(n_factors=50)

NameError: name 'ratings_train' is not defined

In [27]:
from surprise import Reader, Dataset, SVD

In [434]:
svd = SVD(n_factors=50)
surp_train_set = dataset_train.build_full_trainset()
svd.fit(surp_train_set)

In [435]:
svd.fit(surp_train_set)

In [436]:
reader = Reader(rating_scale=(1, 5))

dataset_test = Dataset.load_from_df(ratings_test[['user_id', 'movie_id', 'rating']], reader=reader)

surp_test_set = dataset_test.build_full_trainset().build_testset()

In [427]:
surp_test_set

[(3842, 1645, 2.0),
 (3842, 1225, 5.0),
 (3842, 919, 5.0),
 (3842, 2455, 4.0),
 (3842, 34, 5.0),
 (3842, 1972, 1.0),
 (3842, 235, 5.0),
 (3842, 1589, 4.0),
 (3842, 2413, 3.0),
 (3842, 2, 3.0),
 (3842, 1120, 4.0),
 (3842, 1581, 3.0),
 (3842, 2723, 4.0),
 (3842, 1292, 5.0),
 (3842, 1962, 5.0),
 (3842, 2081, 3.0),
 (3842, 3018, 4.0),
 (3842, 3019, 5.0),
 (3842, 2122, 2.0),
 (3842, 2070, 5.0),
 (3842, 8, 5.0),
 (3842, 539, 2.0),
 (3842, 954, 5.0),
 (3842, 3148, 3.0),
 (3842, 3627, 5.0),
 (3842, 904, 5.0),
 (3842, 1340, 4.0),
 (3842, 189, 4.0),
 (3842, 1041, 4.0),
 (3842, 3060, 5.0),
 (3842, 707, 5.0),
 (3842, 1725, 3.0),
 (3842, 1099, 5.0),
 (3842, 2163, 3.0),
 (3842, 1193, 5.0),
 (3842, 3099, 2.0),
 (3842, 3169, 4.0),
 (3842, 2454, 5.0),
 (3842, 2496, 4.0),
 (3842, 3081, 3.0),
 (2928, 246, 4.0),
 (2928, 2872, 4.0),
 (2928, 1554, 4.0),
 (2928, 2951, 4.0),
 (2928, 2789, 2.0),
 (2928, 1198, 5.0),
 (2928, 2407, 4.0),
 (2928, 2970, 5.0),
 (2928, 3702, 3.0),
 (2928, 1201, 5.0),
 (2928, 3354, 1.

In [439]:
%%time

predictions_svd = svd.test(surp_test_set)

Wall time: 267 ms


In [442]:
predictions_svd

[Prediction(uid=3842, iid=1645, r_ui=2.0, est=3.497999098868502, details={'was_impossible': False}),
 Prediction(uid=3842, iid=1225, r_ui=5.0, est=4.579950773458073, details={'was_impossible': False}),
 Prediction(uid=3842, iid=919, r_ui=5.0, est=4.871649387350518, details={'was_impossible': False}),
 Prediction(uid=3842, iid=2455, r_ui=4.0, est=3.364285346469356, details={'was_impossible': False}),
 Prediction(uid=3842, iid=34, r_ui=5.0, est=4.0956113814118575, details={'was_impossible': False}),
 Prediction(uid=3842, iid=1972, r_ui=1.0, est=2.2643941431776176, details={'was_impossible': False}),
 Prediction(uid=3842, iid=235, r_ui=5.0, est=4.716824437231528, details={'was_impossible': False}),
 Prediction(uid=3842, iid=1589, r_ui=4.0, est=3.5268410824096863, details={'was_impossible': False}),
 Prediction(uid=3842, iid=2413, r_ui=3.0, est=3.747934893639369, details={'was_impossible': False}),
 Prediction(uid=3842, iid=2, r_ui=3.0, est=3.120507206590696, details={'was_impossible': Fal

In [453]:
ratings_test[:]

user_id  movie_id  rating       date
0         3842      1645       2  976513704
1         2928       246       4  971556036
2         5718        25       3  958588034
3           53      1177       5  977986413
4          134         6       2  978038386
...        ...       ...     ...        ...
50000     1389      2987       4  974769357
50001     2012      3712       3  974680318
50002     1679      3219       3  974709659
50003     1890       800       5  974694814
50004      499      2243       3  976212980

[50005 rows x 4 columns]

In [517]:
matrix_demeaned

movie_id      1         2         3         4         5         6     \
user_id                                                                
1         4.943784 -0.056216 -0.056216 -0.056216 -0.056216 -0.056216   
2        -0.123784 -0.123784 -0.123784 -0.123784 -0.123784 -0.123784   
3        -0.052973 -0.052973 -0.052973 -0.052973 -0.052973 -0.052973   
4        -0.021081 -0.021081 -0.021081 -0.021081 -0.021081 -0.021081   
5        -0.161622 -0.161622 -0.161622 -0.161622 -0.161622  1.838378   
...            ...       ...       ...       ...       ...       ...   
6036     -0.742703 -0.742703 -0.742703  1.257297 -0.742703  2.257297   
6037     -0.192703 -0.192703 -0.192703 -0.192703 -0.192703 -0.192703   
6038     -0.020000 -0.020000 -0.020000 -0.020000 -0.020000 -0.020000   
6039     -0.123514 -0.123514 -0.123514 -0.123514 -0.123514 -0.123514   
6040      2.685676 -0.314324 -0.314324 -0.314324 -0.314324 -0.314324   

movie_id      7         8         9         10    ...      3943      3944  \
user_id                                           ...                       
1        -0.056216 -0.056216 -0.056216 -0.056216  ... -0.056216 -0.056216   
2        -0.123784 -0.123784 -0.123784 -0.123784  ... -0.123784 -0.123784   
3        -0.052973 -0.052973 -0.052973 -0.052973  ... -0.052973 -0.052973   
4        -0.021081 -0.021081 -0.021081 -0.021081  ... -0.021081 -0.021081   
5        -0.161622 -0.161622 -0.161622 -0.161622  ... -0.161622 -0.161622   
...            ...       ...       ...       ...  ...       ...       ...   
6036     -0.742703 -0.742703 -0.742703 -0.742703  ... -0.742703 -0.742703   
6037     -0.192703 -0.192703 -0.192703 -0.192703  ... -0.192703 -0.192703   
6038     -0.020000 -0.020000 -0.020000 -0.020000  ... -0.020000 -0.020000   
6039     -0.123514 -0.123514 -0.123514 -0.123514  ... -0.123514 -0.123514   
6040     -0.314324 -0.314324 -0.314324 -0.314324  ... -0.314324 -0.314324   

movie_id      3945      3946      3947      3948      3949      3950  \
user_id                                                                
1        -0.056216 -0.056216 -0.056216 -0.056216 -0.056216 -0.056216   
2        -0.123784 -0.123784 -0.123784 -0.123784 -0.123784 -0.123784   
3        -0.052973 -0.052973 -0.052973 -0.052973 -0.052973 -0.052973   
4        -0.021081 -0.021081 -0.021081 -0.021081 -0.021081 -0.021081   
5        -0.161622 -0.161622 -0.161622 -0.161622 -0.161622 -0.161622   
...            ...       ...       ...       ...       ...       ...   
6036     -0.742703 -0.742703 -0.742703 -0.742703 -0.742703 -0.742703   
6037     -0.192703 -0.192703 -0.192703 -0.192703 -0.192703 -0.192703   
6038     -0.020000 -0.020000 -0.020000 -0.020000 -0.020000 -0.020000   
6039     -0.123514 -0.123514 -0.123514 -0.123514 -0.123514 -0.123514   
6040     -0.314324 -0.314324 -0.314324 -0.314324 -0.314324 -0.314324   

movie_id      3951      3952  
user_id                       
1        -0.056216 -0.056216  
2        -0.123784 -0.123784  
3        -0.052973 -0.052973  
4        -0.021081 -0.021081  
5        -0.161622 -0.161622  
...            ...       ...  
6036     -0.742703 -0.742703  
6037     -0.192703 -0.192703  
6038     -0.020000 -0.020000  
6039     -0.123514 -0.123514  
6040     -0.314324 -0.314324  

[6040 rows x 3700 columns]

In [500]:
import numpy as np
import pandas as pd
from scipy.linalg import sqrtm
def create_utility_matrix(data, formatizer = {'user':0, 'item': 1, 'value': 2}):
    """
        :param data:      Array-like, 2D, nx3
        :param formatizer:pass the formatizer
        :return:          utility matrix (n x m), n=users, m=items
    """
        
    itemField = formatizer['item']
    userField = formatizer['user']
    valueField = formatizer['value']
    userList = data.iloc[:,userField].tolist()
    itemList = data.iloc[:,itemField].tolist()
    valueList = data.iloc[:,valueField].tolist()
    users = list(set(data.iloc[:,userField]))
    items = list(set(data.iloc[:,itemField]))
    users_index = {users[i]: i for i in range(len(users))}
    pd_dict = {item: [np.nan for i in range(len(users))] for item in items}
    for i in range(0,len(data)):
        item = itemList[i]
        user = userList[i]
        value = valueList[i]
    pd_dict[item][users_index[user]] = value
    X = pd.DataFrame(pd_dict)
    X.index = users
        
    itemcols = list(X.columns)
    items_index = {itemcols[i]: i for i in range(len(itemcols))}
    # users_index gives us a mapping of user_id to index of user
    # items_index provides the same for items
    return X, users_index, items_index

In [501]:
def svd(train, k):
    utilMat = np.array(train)
    # the nan or unavailable entries are masked
    mask = np.isnan(utilMat)
    masked_arr = np.ma.masked_array(utilMat, mask)
    item_means = np.mean(masked_arr, axis=0)
    # nan entries will replaced by the average rating for each item
    utilMat = masked_arr.filled(item_means)
    x = np.tile(item_means, (utilMat.shape[0],1))
    # we remove the per item average from all entries.
    # the above mentioned nan entries will be essentially zero now
    utilMat = utilMat - x
    # The magic happens here. U and V are user and item features
    U, s, V=np.linalg.svd(utilMat, full_matrices=False)
    s=np.diag(s)
    # we take only the k most significant features
    s=s[0:k,0:k]
    U=U[:,0:k]
    V=V[0:k,:]
    s_root=sqrtm(s)
    Usk=np.dot(U,s_root)
    skV=np.dot(s_root,V)
    UsV = np.dot(Usk, skV)
    UsV = UsV + x
    print("svd done")
    return UsV

In [507]:
import pandas as pd
import numpy as np
import scipy
data = ratings_train
users = data['user_id'].unique() #list of all users
movies = data['movie_id'].unique() #list of all movies
test = pd.DataFrame(columns=data.columns)
train = pd.DataFrame(columns=data.columns)
test_ratio = 0.2 #fraction of data to be used as test set.
for u in users:
    temp = data[data['user_id'] == u]
    n = len(temp)
    test_size = int(test_ratio*n)
temp = temp.sort_values('date').reset_index()
temp.drop('index', axis=1, inplace=True)
    
dummy_test = temp.loc[n-1-test_size :]
dummy_train = temp.loc[: n-2-test_size]
    
test = pd.concat([test, dummy_test])
train = pd.concat([train, dummy_train])

In [515]:
utilMat, users_index, items_index = create_utility_matrix(ratings_train)

In [516]:
ratings_train

user_id  movie_id  rating       date
0          3539      2478       5  966882141
1          5795       377       2  958143844
2          3513      3526       4  966974170
3          4176       924       5  965330955
4          4657      1960       4  975803771
...         ...       ...     ...        ...
950193     4148       969       5  965343002
950194     4115      2393       5  965363379
950195     3721      1061       4  966225726
950196     4946      1172       4  962641424
950197      505       541       5  976209793

[950198 rows x 4 columns]

In [524]:
svd_res = svd(matrix_demeaned, k=1500)

svd done


In [531]:
resl = abs(svd_res.data  + mean_user_rating)

In [556]:
svd_df = pd.DataFrame( resl, preds.index, preds.columns)

In [557]:
svd_df

movie_id      1         2         3         4         5         6     \
0         4.985687  0.057350  0.069243  0.214329  0.034566  0.018260   
1         0.050401  0.163291  0.129157  0.033503  0.045622  0.048201   
2         0.000355  0.167318  0.043181  0.140347  0.056689  0.065903   
3         0.001847  0.016614  0.023491  0.036155  0.000813  0.010027   
4         0.001059  0.156505  0.170093  0.135271  0.101671  2.070914   
...            ...       ...       ...       ...       ...       ...   
6035      0.031963  0.026823  0.080428  1.795252  0.077423  3.064653   
6036      0.040247  0.055568  0.071870  0.101820  0.075140  0.048972   
6037      0.024291  0.146324  0.055205  0.030204  0.136830  0.031867   
6038      0.010970  0.010456  0.140361  0.196357  0.048408  0.102681   
6039      3.039590  0.023663  0.141859  0.241069  0.004322  0.009348   

movie_id      7         8         9         10    ...      3943      3944  \
0         0.105605  0.110071  0.163400  0.005233  ...  0.018724  0.051680   
1         0.219149  0.042161  0.209533  0.019930  ...  0.072256  0.039631   
2         0.079649  0.108440  0.148433  0.047716  ...  0.106741  0.007996   
3         0.092685  0.022569  0.068550  0.035814  ...  0.124964  0.032064   
4         0.019965  0.156735  0.076693  0.044434  ...  0.038886  0.092016   
...            ...       ...       ...       ...  ...       ...       ...   
6035      0.077898  0.213444  0.021328  0.004945  ...  0.025938  0.044219   
6036      0.115072  0.170646  0.075983  0.134224  ...  0.257640  0.014472   
6037      0.009636  0.077606  0.001656  0.037946  ...  0.049482  0.017145   
6038      0.019116  0.206874  0.133426  0.027464  ...  0.100799  0.067969   
6039      0.088556  0.009328  0.218227  0.061346  ...  0.153538  0.039553   

movie_id      3945      3946      3947      3948      3949      3950  \
0         0.016246  0.028205  0.095987  0.019042  0.049714  0.142084   
1         0.061289  0.029416  0.190475  0.013206  0.169859  0.026616   
2         0.097633  0.128181  0.167282  0.006910  0.099667  0.101965   
3         0.018089  0.014358  0.016155  0.001700  0.007626  0.022648   
4         0.038450  0.022715  0.086153  0.119491  0.088525  0.283924   
...            ...       ...       ...       ...       ...       ...   
6035      0.056345  0.057114  0.160461  0.030195  0.070677  0.163645   
6036      0.019648  0.027662  0.278569  0.038217  0.108227  0.063981   
6037      0.031077  0.001908  0.043446  0.017608  0.075799  0.135487   
6038      0.149938  0.014733  0.161089  0.061188  0.066927  0.106150   
6039      0.000508  0.130835  0.165668  0.022880  0.069425  0.077924   

movie_id      3951      3952  
0         0.006726  0.028519  
1         0.110365  0.079041  
2         0.013715  0.034354  
3         0.004812  0.048830  
4         0.255714  0.001837  
...            ...       ...  
6035      0.113302  0.026462  
6036      0.171893  0.157813  
6037      0.076629  0.022323  
6038      0.181073  0.031300  
6039      0.043438  0.092036  

[6040 rows x 3700 columns]

In [558]:
real_marks = []
predictions = []
for index, row in test_set.iterrows():
    user_id = row['user_id'] - 1
    movie_id = row['movie_id'] - 1
    rating = row['rating']
    if movie_id in movie_ids:
        real_marks.append(rating)
        predictions.append(svd_df.T[user_id][movie_id])
        
        
        
#         print(user_id, movie_id, rating)
#         print(preds.T[user_id][movie_id])

In [559]:
mean_squared_error(real_marks, predictions, squared=False)

3.3611385350606855

In [509]:
def rmse(true, pred):
    # this will be used towards the end
    x = true - pred
    return sum([xi*xi for xi in x])/len(x)
# to test the performance over a different number of features
no_of_features = [8,10,12,14,17]
utilMat, users_index, items_index = create_utility_matrix(ratings_train)
for f in no_of_features: 
    svdout = svd(utilMat, k=f)
    pred = [] #to store the predicted ratings
    for _,row in test.iterrows():
        user = row['user_id']
        item = row['movie_id']
        u_index = users_index[user]
        if item in items_index:
            i_index = items_index[item]
            pred_rating = svdout[u_index, i_index]
        else:
            pred_rating = np.mean(svdout[u_index, :])
        pred.append(pred_rating)
        print(rmse(row['rating'], pred_rating))
print('bnju', rmse(test['rating'], pred))

KeyboardInterrupt: 